export default [
  {
    twoFactorEnabled: false,
    phoneNumberConfirmed: false,
    emailConfirmed: false,
    normalizedEmail: 'VVTHANH010@GMAIL.COM',
    email: 'vvthanh010@gmail.com',
    normalizedUserName: 'VVTHANH269@GMAIL.COM',
    userName: 'vvthanh269@gmail.com',
    id: '0ab2f9fd-bedd-44f3-89e2-b08a31476784',
    lockoutEnabled: true,
    accessFailedCount: 0,
    roles: ['HocVien', 'Admin', 'Marketing', 'TroGiang'],
  },
  {
    twoFactorEnabled: false,
    phoneNumberConfirmed: false,
    emailConfirmed: false,
    normalizedEmail: 'TROGIANG@HVITCLAN.VN',
    email: 'trogiang@hvitclan.vn',
    normalizedUserName: 'TROGIANG@HVITCLAN.VN',
    userName: 'trogiang@hvitclan.vn',
    id: '0bf53099-b70a-44cc-93b1-4a9f1694c1fc',
    lockoutEnabled: true,
    accessFailedCount: 0,
    roles: ['Admin'],
  },
  {
    twoFactorEnabled: false,
    phoneNumberConfirmed: false,
    emailConfirmed: false,
    normalizedEmail: 'DO.QUANGANH99ZZ@GMAIL.COM',
    email: 'do.quanganh99zz@gmail.com',
    normalizedUserName: 'DO.QUANGANH99ZZ@GMAIL.COM',
    userName: 'do.quanganh99zz@gmail.com',
    id: '69a7b83a-e989-4827-91d3-59a65b50f1a1',
    lockoutEnabled: true,
    accessFailedCount: 0,
    roles: ['HocVien', 'Admin', 'Marketing', 'TroGiang'],
  },
  {
    lockoutEnd: '2021-10-03T01:50:24.6620896+00:00',
    twoFactorEnabled: false,
    phoneNumberConfirmed: false,
    emailConfirmed: false,
    normalizedEmail: 'ADMIN@HVITCLAN.VN',
    email: 'admin@hvitclan.vn',
    normalizedUserName: 'ADMIN@HVITCLAN.VN',
    userName: 'admin@hvitclan.vn',
    id: 'bd21c6be-78e5-44e3-bc9f-e359e1496aa4',
    lockoutEnabled: true,
    accessFailedCount: 0,
    roles: ['Admin', 'TroGiang'],
  },
  {
    twoFactorEnabled: false,
    phoneNumberConfirmed: false,
    emailConfirmed: false,
    normalizedEmail: 'TRANQUANGKHANH92@GMAIL.COM',
    email: 'tranquangkhanh92@gmail.com',
    normalizedUserName: 'TRANQUANGKHANH92@GMAIL.COM',
    userName: 'tranquangkhanh92@gmail.com',
    id: 'c7670931-146b-4a98-ae6e-8ea8313a06c0',
    lockoutEnabled: true,
    accessFailedCount: 3,
    roles: ['HocVien', 'Admin', 'TroGiang'],
  },
  {
    twoFactorEnabled: false,
    phoneNumberConfirmed: false,
    emailConfirmed: false,
    normalizedEmail: 'CUONGVTH191023@GMAIL.COM',
    email: 'cuongvth191023@gmail.com',
    normalizedUserName: 'CUONGVTH191023@GMAIL.COM',
    userName: 'cuongvth191023@gmail.com',
    id: 'd4742766-d5c0-4d36-b01a-ee30e0d2247c',
    lockoutEnabled: true,
    accessFailedCount: 0,
    roles: ['HocVien', 'Admin', 'TroGiang'],
  },
  {
    twoFactorEnabled: false,
    phoneNumberConfirmed: false,
    emailConfirmed: false,
    normalizedEmail: 'NTTHINH1991@GMAIL.COM',
    email: 'ntthinh1991@gmail.com',
    normalizedUserName: 'NTTHINH1991@GMAIL.COM',
    userName: 'ntthinh1991@gmail.com',
    id: 'd4b70e82-c229-4f70-b13e-aed1edfa824a',
    lockoutEnabled: true,
    accessFailedCount: 0,
    roles: ['HocVien', 'Admin', 'TroGiang'],
  },
  {
    twoFactorEnabled: false,
    phoneNumberConfirmed: false,
    emailConfirmed: false,
    normalizedEmail: 'LETHIKIMNGAN2606@GMAIL.COM',
    email: 'lethikimngan2606@gmail.com',
    normalizedUserName: 'LETHIKIMNGAN2606@GMAIL.COM',
    userName: 'lethikimngan2606@gmail.com',
    id: 'd9c577cb-d2cc-48e6-a490-26605559486a',
    lockoutEnabled: true,
    accessFailedCount: 0,
    roles: ['HocVien', 'Admin', 'TroGiang'],
  },
  {
    twoFactorEnabled: false,
    phoneNumberConfirmed: false,
    emailConfirmed: false,
    normalizedEmail: 'NGUYENCUONGZTH@GMAIL.COM',
    email: 'nguyencuongzth@gmail.com',
    normalizedUserName: 'NGUYENCUONGZTH@GMAIL.COM',
    userName: 'nguyencuongzth@gmail.com',
    id: 'f45fdb88-f85e-4680-a037-f36ff96b70ce',
    lockoutEnabled: true,
    accessFailedCount: 0,
    roles: ['HocVien'],
  },
  {
    twoFactorEnabled: false,
    phoneNumberConfirmed: false,
    emailConfirmed: false,
    normalizedEmail: 'NGUYENMY19031998@GMAIL.COM',
    email: 'nguyenmy19031998@gmail.com',
    normalizedUserName: 'NGUYENMY19031998@GMAIL.COM',
    userName: 'nguyenmy19031998@gmail.com',
    id: 'f46f8cb1-d427-4b27-939e-bd6738fe4681',
    lockoutEnabled: true,
    accessFailedCount: 0,
    roles: ['HocVien'],
  },
  {
    twoFactorEnabled: false,
    phoneNumberConfirmed: false,
    phoneNumber: '',
    emailConfirmed: false,
    normalizedEmail: 'N20DCCN005@STUDENT.PTITHCM.EDU.VN',
    email: 'n20dccn005@student.ptithcm.edu.vn',
    normalizedUserName: 'N20DCCN005@STUDENT.PTITHCM.EDU.VN',
    userName: 'n20dccn005@student.ptithcm.edu.vn',
    id: 'f47cdc78-1167-46cb-8cd6-b4e7a216df08',
    lockoutEnabled: true,
    accessFailedCount: 0,
    roles: ['HocVien'],
  },
  {
    twoFactorEnabled: false,
    phoneNumberConfirmed: false,
    emailConfirmed: false,
    normalizedEmail: 'LEDUYDAT99@GMAIL.COM',
    email: 'leduydat99@gmail.com',
    normalizedUserName: 'LEDUYDAT99@GMAIL.COM',
    userName: 'leduydat99@gmail.com',
    id: 'f49f05ac-521e-41f5-b8e3-793dadb68ae5',
    lockoutEnabled: true,
    accessFailedCount: 0,
    roles: ['HocVien'],
  },
  {
    twoFactorEnabled: false,
    phoneNumberConfirmed: false,
    emailConfirmed: false,
    normalizedEmail: 'PHAMTHUAN2512@GMAIL.COM',
    email: 'phamthuan2512@gmail.com',
    normalizedUserName: 'PHAMTHUAN2512@GMAIL.COM',
    userName: 'phamthuan2512@gmail.com',
    id: 'f4ea5ae9-fa1b-4406-979a-6bab4e9b51d9',
    lockoutEnabled: true,
    accessFailedCount: 0,
    roles: ['HocVien'],
  },
  {
    twoFactorEnabled: false,
    phoneNumberConfirmed: false,
    emailConfirmed: false,
    normalizedEmail: 'TRUONGMANHQUANG2K3@GMAIL.COM',
    email: 'truongmanhquang2k3@gmail.com',
    normalizedUserName: 'TRUONGMANHQUANG2K3@GMAIL.COM',
    userName: 'truongmanhquang2k3@gmail.com',
    id: 'f4ebab39-8e62-4b89-bae7-82604d63c687',
    lockoutEnabled: true,
    accessFailedCount: 0,
    roles: ['HocVien'],
  },
  {
    twoFactorEnabled: false,
    phoneNumberConfirmed: false,
    emailConfirmed: false,
    normalizedEmail: 'PMHUNG.10A4KX2001@GMAIL.COM',
    email: 'pmhung.10a4kx2001@gmail.com',
    normalizedUserName: 'PMHUNG.10A4KX2001@GMAIL.COM',
    userName: 'pmhung.10a4kx2001@gmail.com',
    id: 'f519cbf1-71c2-41c6-bc08-b2c5d15b281f',
    lockoutEnabled: true,
    accessFailedCount: 0,
    roles: ['HocVien'],
  },
  {
    twoFactorEnabled: false,
    phoneNumberConfirmed: false,
    emailConfirmed: false,
    normalizedEmail: 'TROIOI1071999@GMAIL.COM',
    email: 'troioi1071999@gmail.com',
    normalizedUserName: 'TROIOI1071999@GMAIL.COM',
    userName: 'troioi1071999@gmail.com',
    id: 'f520d8b8-f48c-4188-bc44-74362f98a295',
    lockoutEnabled: true,
    accessFailedCount: 0,
    roles: ['HocVien'],
  },
  {
    lockoutEnd: '2020-08-14T11:41:55.1077364+00:00',
    twoFactorEnabled: false,
    phoneNumberConfirmed: false,
    phoneNumber: '0384953707',
    emailConfirmed: false,
    normalizedEmail: 'HUYHOANGPYTN@GMAIL.COM',
    email: 'huyhoangpytn@gmail.com',
    normalizedUserName: 'HUYHOANGPYTN@GMAIL.COM',
    userName: 'huyhoangpytn@gmail.com',
    id: 'f5263d60-bf90-4811-98b2-0d69ec435fb0',
    lockoutEnabled: true,
    accessFailedCount: 0,
    roles: ['HocVien'],
  },
  {
    twoFactorEnabled: false,
    phoneNumberConfirmed: false,
    emailConfirmed: false,
    normalizedEmail: 'BUIMANHCUONG10803@GMAIL.COM',
    email: 'buimanhcuong10803@gmail.com',
    normalizedUserName: 'BUIMANHCUONG10803@GMAIL.COM',
    userName: 'buimanhcuong10803@gmail.com',
    id: 'f571a6f6-21e0-4b8a-896e-1a74063be7cd',
    lockoutEnabled: true,
    accessFailedCount: 0,
    roles: ['HocVien'],
  },
  {
    twoFactorEnabled: false,
    phoneNumberConfirmed: false,
    emailConfirmed: false,
    normalizedEmail: 'NGOCLINH.TNKT@GMAIL.COM',
    email: 'ngoclinh.tnkt@gmail.com',
    normalizedUserName: 'NGOCLINH.TNKT@GMAIL.COM',
    userName: 'ngoclinh.tnkt@gmail.com',
    id: 'f57fa30e-6dab-49ab-87ad-7c0e4fc0458f',
    lockoutEnabled: true,
    accessFailedCount: 0,
    roles: ['HocVien'],
  },
  {
    twoFactorEnabled: false,
    phoneNumberConfirmed: false,
    emailConfirmed: false,
    normalizedEmail: 'PHUONGANH06012007@GMAIL.COM',
    email: 'phuonganh06012007@gmail.com',
    normalizedUserName: 'PHUONGANH06012007@GMAIL.COM',
    userName: 'phuonganh06012007@gmail.com',
    id: 'f5cb8aff-9187-4672-835a-5e6bfb7380ec',
    lockoutEnabled: true,
    accessFailedCount: 0,
    roles: ['HocVien'],
  },
  {
    twoFactorEnabled: false,
    phoneNumberConfirmed: false,
    phoneNumber: '0968813023',
    emailConfirmed: false,
    normalizedEmail: 'PROUDOFYOU217@GMAIL.COM',
    email: 'proudofyou217@gmail.com',
    normalizedUserName: 'PROUDOFYOU217@GMAIL.COM',
    userName: 'proudofyou217@gmail.com',
    id: 'f5edf005-32d1-444b-a7e4-16a8bd4dfe32',
    lockoutEnabled: true,
    accessFailedCount: 2,
    roles: ['HocVien'],
  },
  {
    twoFactorEnabled: false,
    phoneNumberConfirmed: false,
    emailConfirmed: false,
    normalizedEmail: 'KIEUTAM0801@GMAIL.COM',
    email: 'kieutam0801@gmail.com',
    normalizedUserName: 'KIEUTAM0801@GMAIL.COM',
    userName: 'kieutam0801@gmail.com',
    id: 'f602ff44-9937-4b89-813b-f601a3a3500b',
    lockoutEnabled: true,
    accessFailedCount: 0,
    roles: ['HocVien'],
  },
  {
    twoFactorEnabled: false,
    phoneNumberConfirmed: false,
    phoneNumber: '090909090',
    emailConfirmed: false,
    normalizedEmail: 'TRANPHUOC@HOTMAIL.COM',
    email: 'tranphuoc@hotmail.com',
    normalizedUserName: 'TRANPHUOC@HOTMAIL.COM',
    userName: 'tranphuoc@hotmail.com',
    id: 'f63734d3-750f-4308-bd2a-b93d6785f24e',
    lockoutEnabled: true,
    accessFailedCount: 0,
    roles: ['HocVien'],
  },
  {
    twoFactorEnabled: false,
    phoneNumberConfirmed: false,
    emailConfirmed: false,
    normalizedEmail: 'TUNGTRAN962003@GMAIL.COM',
    email: 'tungtran962003@gmail.com',
    normalizedUserName: 'TUNGTRAN962003@GMAIL.COM',
    userName: 'tungtran962003@gmail.com',
    id: 'f6792e1d-9889-4b3f-bc7c-0ccd4fff9b6b',
    lockoutEnabled: true,
    accessFailedCount: 0,
    roles: ['HocVien'],
  },
  {
    lockoutEnd: '2021-03-26T08:28:41.0817745+00:00',
    twoFactorEnabled: false,
    phoneNumberConfirmed: false,
    emailConfirmed: false,
    normalizedEmail: 'DOUX795@GMAIL.COM',
    email: 'doux795@gmail.com',
    normalizedUserName: 'DOUX795@GMAIL.COM',
    userName: 'doux795@gmail.com',
    id: 'f69bfbcb-c4ae-40b4-8946-22f9803ea03b',
    lockoutEnabled: true,
    accessFailedCount: 0,
    roles: ['HocVien'],
  },
  {
    twoFactorEnabled: false,
    phoneNumberConfirmed: false,
    emailConfirmed: false,
    normalizedEmail: 'NGHIEN87@GMAIL.COM',
    email: 'nghien87@gmail.com',
    normalizedUserName: 'NGHIEN87@GMAIL.COM',
    userName: 'nghien87@gmail.com',
    id: 'f6e98419-46fb-445d-b901-a52dae6d66c3',
    lockoutEnabled: true,
    accessFailedCount: 0,
    roles: ['HocVien'],
  },
  {
    twoFactorEnabled: false,
    phoneNumberConfirmed: false,
    emailConfirmed: false,
    normalizedEmail: 'HYENBDAP@GMAIL.COM',
    email: 'hyenbdap@gmail.com',
    normalizedUserName: 'HYENBDAP@GMAIL.COM',
    userName: 'hyenbdap@gmail.com',
    id: 'f78f46f3-4fc4-4ebc-bb89-8ab2774bae6b',
    lockoutEnabled: true,
    accessFailedCount: 0,
    roles: ['HocVien'],
  },
  {
    twoFactorEnabled: false,
    phoneNumberConfirmed: false,
    emailConfirmed: false,
    normalizedEmail: 'THMT19997@GMAIL.COM',
    email: 'thmt19997@gmail.com',
    normalizedUserName: 'THMT19997@GMAIL.COM',
    userName: 'thmt19997@gmail.com',
    id: 'f7930b75-2a3a-4493-9ad1-1cff191358c3',
    lockoutEnabled: true,
    accessFailedCount: 0,
    roles: ['HocVien'],
  },
  {
    twoFactorEnabled: false,
    phoneNumberConfirmed: false,
    emailConfirmed: false,
    normalizedEmail: 'BLACKHOLEYOSHITSUNE@GMAIL.COM',
    email: 'blackholeyoshitsune@gmail.com',
    normalizedUserName: 'BLACKHOLEYOSHITSUNE@GMAIL.COM',
    userName: 'blackholeyoshitsune@gmail.com',
    id: 'f7c7c624-b70a-41f6-8739-705190a5bb94',
    lockoutEnabled: true,
    accessFailedCount: 0,
    roles: ['HocVien'],
  },
  {
    twoFactorEnabled: false,
    phoneNumberConfirmed: false,
    emailConfirmed: false,
    normalizedEmail: 'SONGOKU9720@GMAIL.COM',
    email: 'songoku9720@gmail.com',
    normalizedUserName: 'SONGOKU9720@GMAIL.COM',
    userName: 'songoku9720@gmail.com',
    id: 'f7e94ea5-8acf-4a82-af91-a9ea06961958',
    lockoutEnabled: true,
    accessFailedCount: 0,
    roles: ['HocVien'],
  },
  {
    twoFactorEnabled: false,
    phoneNumberConfirmed: false,
    emailConfirmed: false,
    normalizedEmail: 'DUC.HTMEC@GMAIL.COM',
    email: 'duc.htmec@gmail.com',
    normalizedUserName: 'DUC.HTMEC@GMAIL.COM',
    userName: 'duc.htmec@gmail.com',
    id: 'f878b296-b7c1-442c-944d-fce3a92dd044',
    lockoutEnabled: true,
    accessFailedCount: 0,
    roles: ['HocVien'],
  },
  {
    twoFactorEnabled: false,
    phoneNumberConfirmed: false,
    emailConfirmed: false,
    normalizedEmail: 'SKYWARK98@GMAIL.COM',
    email: 'skywark98@gmail.com',
    normalizedUserName: 'SKYWARK98@GMAIL.COM',
    userName: 'skywark98@gmail.com',
    id: 'f87acd83-87eb-40e8-900e-cbbef6cc452d',
    lockoutEnabled: true,
    accessFailedCount: 0,
    roles: ['HocVien'],
  },
  {
    twoFactorEnabled: false,
    phoneNumberConfirmed: false,
    emailConfirmed: false,
    normalizedEmail: 'TRUONG98HIRO@GMAIL.COM',
    email: 'truong98hiro@gmail.com',
    normalizedUserName: 'TRUONG98HIRO@GMAIL.COM',
    userName: 'truong98hiro@gmail.com',
    id: 'f8917a40-5f43-4435-a616-42d34fb7fe68',
    lockoutEnabled: true,
    accessFailedCount: 0,
    roles: ['HocVien'],
  },
];
